import { Inter } from 'next/font/google';
import './globals.css'; // Adjust the path as needed
import Navbar from '@/components/Navbar'; // Ensure this path is correct

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Hunting Coder',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} m-0 p-0`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
